backend:
  name: github
  repo: jschmidtnj/annettevonbrandis.com
  branch: main

site_url: https://annetteportfolio.netlify.app

locale: en
media_folder: ../assets
public_folder: ../assets

collections:
  - name: projects
    label: Projects
    folder: web/content/pages/projects
    create: true
    fields:
      - name: image
        label: Image
        widget: image
      - name: title
        label: Title
        widget: string
      - name: caption
        label: Caption
        widget: string
      - name: description
        label: Description
        widget: markdown
      - name: story
        label: Story
        widget: markdown
      - name: images
        label: Images
        widget: list
        fields:
          - name: name
            label: Name
            widget: string
          - name: image
            label: Image
            widget: image
          - name: year
            label: Year
            widget: number
            value_type: int
            default: 2023
          - name: width
            label: Width
            widget: number
            value_type: float
            min: 1
            max: 12
            default: 6
  - name: pages
    label: Pages
    files:
      - label: Students Page
        name: students
        file: web/content/pages/students.md
        fields:
          - name: description
            label: Description
            widget: markdown
          - name: images
            label: Images
            widget: list
            fields:
              - name: caption
                label: Caption
                widget: string
              - name: showCaption
                label: Show Caption
                widget: boolean
                default: true
              - name: image
                label: Image
                widget: image
              - name: year
                label: Year
                widget: number
                value_type: int
                default: 2023
              - name: width
                label: Width
                widget: number
                value_type: float
                min: 1
                max: 12
                default: 3
      - label: Art Page
        name: art
        file: web/content/pages/art.md
        fields:
          - name: images
            label: Images
            widget: list
            fields:
              - name: caption
                label: Caption
                widget: string
              - name: showCaption
                label: Show Caption
                widget: boolean
                default: true
              - name: image
                label: Image
                widget: image
              - name: year
                label: Year
                widget: number
                value_type: int
                default: 2023
              - name: width
                label: Width
                widget: number
                value_type: float
                min: 1
                max: 12
                default: 3
      - label: About Page
        name: about
        file: web/content/pages/about.md
        fields:
          - name: image
            label: Image
            widget: image
          - name: biography
            label: Biography
            widget: markdown
          - name: education
            label: Education
            widget: markdown
          - name: awards
            label: Awards
            widget: markdown
