backend:
  name: github
  repo: jschmidtnj/annettevonbrandis.com
  branch: main

site_url: https://annetteportfolio.netlify.app

locale: en
media_folder: ''

collections:
  - name: pages
    label: Pages
    media_folder: ../assets
    public_folder: ../assets
    files:
      - label: Home Page
        name: home
        file: web/content/pages/home.md
        fields:
          - name: intro
            label: Intro
            widget: markdown
      - label: Professional Work Page
        name: projects
        file: web/content/pages/projects.md
        fields:
          - name: description
            label: Description
            widget: markdown
      - label: Student Work Page
        name: students
        file: web/content/pages/students.md
        fields:
          - name: description
            label: Description
            widget: markdown
      - label: Community Page
        name: art
        file: web/content/pages/art.md
        fields:
          - name: images
            label: Images
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
              - name: image
                label: Image
                widget: image
              - name: year
                label: Year
                widget: number
                value_type: int
                default: 2023
              - name: width
                label: Width
                widget: number
                value_type: float
                min: 1
                max: 12
                default: 3
      - label: About Page
        name: about
        file: web/content/pages/about.md
        fields:
          - name: image
            label: Image
            widget: image
          - name: biography
            label: Biography
            widget: markdown
          - name: education
            label: Education
            widget: markdown
          - name: awards
            label: Awards
            widget: markdown
          - name: images
            label: Images
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
              - name: image
                label: Image
                widget: image
              - name: year
                label: Year
                widget: number
                value_type: int
                default: 2023
              - name: width
                label: Width
                widget: number
                value_type: float
                min: 1
                max: 12
                default: 3
  - name: projects
    label: Professional Work
    folder: web/content/pages/projects
    create: true
    media_folder: ../../assets
    public_folder: ../../assets
    fields:
      - name: title
        label: Title
        widget: string
      - name: year
        label: Year
        widget: number
        value_type: int
        default: 2023
      - name: image
        label: Image
        widget: image
      - name: caption
        label: Caption
        widget: string
      - name: description
        label: Description
        widget: markdown
      - name: story
        label: Story
        widget: markdown
      - name: images
        label: Images
        widget: list
        fields:
          - name: name
            label: Name
            widget: string
          - name: image
            label: Image
            widget: image
          - name: width
            label: Width
            widget: number
            value_type: float
            min: 1
            max: 12
            default: 6
  - name: students
    label: Student Work
    folder: web/content/pages/students
    create: true
    media_folder: ../../assets
    public_folder: ../../assets
    fields:
      - name: title
        label: Title
        widget: string
      - name: year
        label: Year
        widget: number
        value_type: int
        default: 2023
      - name: image
        label: Image
        widget: image
      - name: caption
        label: Caption
        widget: string
      - name: description
        label: Description
        widget: markdown
      - name: story
        label: Story
        widget: markdown
      - name: images
        label: Images
        widget: list
        fields:
          - name: name
            label: Name
            widget: string
          - name: image
            label: Image
            widget: image
          - name: width
            label: Width
            widget: number
            value_type: float
            min: 1
            max: 12
            default: 6
